name: recipe_finder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2

  #State management
  flutter_bloc:

  #Localization
  easy_localization: ^3.0.1

  #Cache
  hive_flutter: ^1.1.0

  #Network
  dio: ^4.0.6

  #Google
  connectivity_plus:
  change_app_package_name:
  intl:
  email_validator: ^2.0.1
  dropdown_search: ^5.0.3
  page_transition: ^2.0.9
  lottie: ^1.4.2
  avatar_glow: ^2.0.2
  speech_to_text: ^6.1.1


  #Animation
  flutter_svg: ^1.1.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  hive_generator: ^1.1.3
  







  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/poppins/Poppins-Bold.ttf
          weight: 600
        - asset: asset/font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: asset/font/poppins/Poppins-Light.ttf
          weight: 300
        - asset: asset/font/poppins/Poppins-Regular.ttf
          weight: 400

  assets:
    
    - asset/navigation_bar_icon/
    - asset/language/
    - asset/font/
    - asset/png/
    - asset/svg/
    - asset/lotties/
  uses-material-design: true

































