name: recipe_finder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #State management
  flutter_bloc:

  #Localization
  easy_localization: ^3.0.1

  #Cache
  hive_flutter: ^1.1.0

  #Network
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  vexana: ^3.3.2
  dio:

  #Google
  cupertino_icons: ^1.0.2
  connectivity_plus:
  change_app_package_name:
  intl:
  email_validator: ^2.0.1
  dropdown_search: ^5.0.3
  page_transition: ^2.0.9
  avatar_glow: ^2.0.2
  speech_to_text: ^6.1.1
  video_player: ^2.4.9
  chewie: ^1.3.6
  share_plus: ^6.3.0
  dotted_border: ^2.0.0+3
  flutter_launcher_icons: ^0.11.0
  fluttertoast: ^8.1.2
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^5.0.7
  font_awesome_flutter:


  #Animation
  flutter_svg: ^1.1.6
  lottie: ^2.2.0
  swipe_cards: ^1.0.0
  swipable_stack: ^2.0.0
  device_preview: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  hive_generator: ^1.1.3
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/png/app_icon2.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/poppins/Poppins-Bold.ttf
          weight: 600
        - asset: asset/font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: asset/font/poppins/Poppins-Light.ttf
          weight: 300
        - asset: asset/font/poppins/Poppins-Regular.ttf
          weight: 400

  assets:
    
    - asset/navigation_bar_icon/
    - asset/language/
    - asset/font/
    - asset/png/
    - asset/svg/
    - asset/jpg/
    - asset/lotties/
    - asset/video/

  uses-material-design: true

































